//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iphaser.Agenti.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimentiRipetitivi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovimentiRipetitivi()
        {
            this.Movimenti = new HashSet<Movimenti>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDContoCorrente { get; set; }
        public Nullable<System.DateTime> DataScadenza { get; set; }
        public string Descrizione { get; set; }
        public Nullable<decimal> Importo { get; set; }
        public Nullable<int> IDCategoriaIphase { get; set; }
        public string Frequenza { get; set; }
        public Nullable<System.DateTime> DataUltimaElaborazione { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimenti> Movimenti { get; set; }
    }
}
