//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iphaser.Agenti.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ReportCategorieIpase
    {
        public Nullable<int> Anno { get; set; }
        public Nullable<int> Mese { get; set; }
        public Nullable<int> IDCategoriaIphase { get; set; }
        public string Descrizione { get; set; }
        public long RN { get; set; }
        public Nullable<decimal> Totale { get; set; }
    }
}
