//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMoneyManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyMoneyManagerEntities : DbContext
    {
        public MyMoneyManagerEntities()
            : base("name=MyMoneyManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carte> Carte { get; set; }
        public virtual DbSet<CategorieIphase> CategorieIphase { get; set; }
        public virtual DbSet<CategorieUbiBanca> CategorieUbiBanca { get; set; }
        public virtual DbSet<ContiCorrente> ContiCorrente { get; set; }
        public virtual DbSet<Function> Function { get; set; }
        public virtual DbSet<Movimenti> Movimenti { get; set; }
        public virtual DbSet<PagamentiIphase> PagamentiIphase { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleFunction> RoleFunction { get; set; }
        public virtual DbSet<tReportCategorieMeseIpase> tReportCategorieMeseIpase { get; set; }
        public virtual DbSet<tReportCategorieMeseUbi> tReportCategorieMeseUbi { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Log4Net> Log4Net { get; set; }
        public virtual DbSet<Keywords> Keywords { get; set; }
    }
}
