//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMoneyManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleFunction
    {
        public int IDRoleFunction { get; set; }
        public Nullable<int> IDRole_Code { get; set; }
        public Nullable<int> IDFunction_Code { get; set; }
        public Nullable<short> Permission { get; set; }
    }
}
