//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMoneyManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tReportCategorieMeseIpase
    {
        public int ID { get; set; }
        public Nullable<int> IDCategoria { get; set; }
        public Nullable<int> Anno { get; set; }
        public Nullable<int> Mese { get; set; }
        public Nullable<decimal> Importo { get; set; }
    
        public virtual CategorieIphase CategorieIphase { get; set; }
    }
}
