//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMoneyManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int User_ID { get; set; }
        public string Username { get; set; }
        public Nullable<int> IDRole_Code { get; set; }
        public string Password { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string Email { get; set; }
        public Nullable<short> Logged { get; set; }
        public string Logged_IP { get; set; }
        public Nullable<int> CanUpdate { get; set; }
        public string LastVersion { get; set; }
    }
}
